//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriangleProject.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriangleProject.Client.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חזרה.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניתן לפרסום.
        /// </summary>
        public static string CanPublish {
            get {
                return ResourceManager.GetString("CanPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מסיחים.
        /// </summary>
        public static string GameAnswersCount {
            get {
                return ResourceManager.GetString("GameAnswersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד.
        /// </summary>
        public static string GameCode {
            get {
                return ResourceManager.GetString("GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קטגוריה נכונה.
        /// </summary>
        public static string GameCorrectCategory {
            get {
                return ResourceManager.GetString("GameCorrectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיקה.
        /// </summary>
        public static string GameDelete {
            get {
                return ResourceManager.GetString("GameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכה.
        /// </summary>
        public static string GameEdit {
            get {
                return ResourceManager.GetString("GameEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הודעת סיום.
        /// </summary>
        public static string GameEndMessage {
            get {
                return ResourceManager.GetString("GameEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזהה משחק.
        /// </summary>
        public static string GameID {
            get {
                return ResourceManager.GetString("GameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המשחק.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסום משחק.
        /// </summary>
        public static string GamePublish {
            get {
                return ResourceManager.GetString("GamePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גזע השאלה.
        /// </summary>
        public static string GameQuestion {
            get {
                return ResourceManager.GetString("GameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות משחק.
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קטגוריה לא נכונה.
        /// </summary>
        public static string GameWrongCategory {
            get {
                return ResourceManager.GetString("GameWrongCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איך משחקים.
        /// </summary>
        public static string How_to_play {
            get {
                return ResourceManager.GetString("How to play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסום.
        /// </summary>
        public static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחק חדש.
        /// </summary>
        public static string New_Game {
            get {
                return ResourceManager.GetString("New Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פורטל&quot;מ.
        /// </summary>
        public static string Portelem {
            get {
                return ResourceManager.GetString("Portelem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסום.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירה.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירת הגדרות.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחק זה אינו עומד בתנאי הפרסום.
        /// </summary>
        public static string The_game_does_not_meet_the_conditions_of_publishing {
            get {
                return ResourceManager.GetString("The game does not meet the conditions of publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסרת פרסום.
        /// </summary>
        public static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
    }
}
