//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriangleProject.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriangleProject.Client.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד משחק.
        /// </summary>
        public static string GameCode {
            get {
                return ResourceManager.GetString("GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיקת משחק.
        /// </summary>
        public static string GameDelete {
            get {
                return ResourceManager.GetString("GameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת משחק.
        /// </summary>
        public static string GameEdit {
            get {
                return ResourceManager.GetString("GameEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משחק.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסום.
        /// </summary>
        public static string GamePublish {
            get {
                return ResourceManager.GetString("GamePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איך משחקים.
        /// </summary>
        public static string How_to_play {
            get {
                return ResourceManager.GetString("How to play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסום.
        /// </summary>
        public static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פורטל&quot;מ.
        /// </summary>
        public static string Portelem {
            get {
                return ResourceManager.GetString("Portelem", resourceCulture);
            }
        }
    }
}
